version: "3.8"

services:
  bot:
    build: .
    container_name: discord-bot
    env_file:
      - .env        # fichier .env à créer sur le serveur
    restart: always # redémarre automatiquement en cas de crash
